apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: usagedata
  labels:
    app: usagedata
spec:
  rules:
  - host: kos-mvp.msa.kt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: usagedata
          servicePort: 8080
