apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  labels:
    app: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: kos-cluster.icp:8500/kos-mvp/kafka-consumer
        imagePullPolicy: "Always"
        env:
         - name: target.service.name
           value: "usagedata-db:8080"
        ports:
         - containerPort: 8080
  strategy:
    rollingUpdate:
      maxSurge: 50%
