apiVersion: apps/v1
kind: Deployment
metadata:
  name: usagedata-db
  labels:
    app: usagedata-db
spec:
  selector:
    matchLabels:
      app: usagedata-db
  template:
    metadata:
      labels:
        app: usagedata-db
    spec:
      containers:
      - name: usagedata-db
        image: kos-cluster.icp:8500/kos-mvp/usagedata-db
        imagePullPolicy: IfNotPresent
        env:
          - name: target.service.name
            value: "manage-cache:8080"
          - name: POSTGRES_ENV_IP
            value: "postgres-vm"
          - name: POSTGRES_ENV_PORT
            value: "5432"
          - name: POSTGRES_ENV_DB
            value: "garage"
        ports:
          - containerPort: 8080
