kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-nfs-volume
  labels:
    type: local
    app: postgres
spec:
#  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/nfs/postgres
    server: ktis-nfs.container.ipc.kt.com
#  hostPath:
#    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-nfs-claim
  labels:
    app: postgres
spec:
#  storageClassName: manual
  selector:
    matchLabels:
      type: local
      app: postgres
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
