apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-kos-mvp-postgres
spec:
  host: kos-mvp.postgres.container.ipc.kt.com
  port:
    targetPort: 80
#  path: "/"
  to:
    kind: Service
    name: postgres
    weight: 100
  wildcardPolicy: None
